### PR TITLE
Fixed detection of joystick axis

### PR DESCRIPTION
**Pull request by Techwolf**
Added some helpful console info the both the developer and end user can use to troubleshoot.
Added button detentions.
Code ported from SDL that is BSD licensed.

### CODE REVIEW

**Comment by Techwolf** [comment]
I used github editor, feel free to clean up the code as needed. Not used to non-LL code formatting.

**Comment by janoc** [comment]
Thanks for the patch. 

Unfortunately, it is not completely correct - it seems that some devices, such as my SpaceBall 5000 and the SpaceNavigators return the axes as relative (using EV_REL events), not absolute (EV_ABS) on some kernel versions (I have a Mageia 4.1.8-desktop-1.mga5 for the record). 

SDL makes the same mistake, so their joystick support code doesn't work with these devices. That was one reason why I switched to the raw evdev instead. The code needs to take that into account. 

I remember this has changed between some kernel versions in the past at least once (from 2.6.35 onwards). It is possible that the kernel driver behaviour has changed again. The polling code handles both EV_ABS and EV_REL events, in order to be sure to work (the data are the same, only the event type is different). 

I will modify the code to try both types of axes when detecting them.

**Comment by janoc** [comment]
The second issue are the debug printf statements - I prefer to wrap those in an #ifdef and not print those things by default. Libraries spewing out debug info unconditionally are a bad mojo.

**Comment by janoc** [comment]
Please have a look at the current 0.8, it includes the changes from you plus fixes for the relative axes. I have also cleaned up the debug prints, that is really not very useful to leave there, it would only pollute the logs.

**Comment by Techwolf** [comment]
That is why I fallback to 6 axis and 32 buttons, the code before would get zero, breaking my Spacenav. :-) Will be looking over the code. The "debug" stuff is helpfull for the end user as to why there Spacenav isn't working. At lease print what device it is using so the end user doesn't pull there hair out why it isn't working.

**Comment by Techwolf** [comment]
I notice the small test file. That can be handy for devs and end users. :-) I'll add to my packaged builds, or more speciously, by gentoo overlay.

**Comment by Techwolf** [comment]
I'll test stuff within the next couple days and will report back here.

**Comment by janoc** [comment]
I have kept the fallback in case of a strange device that doesn't report the buttons/axes, so that should still work fine. 

Re debug prints - those are not really useful, certainly not to an end user. It assumes that SL is launched from command line (in order to have the console log in the first place) and that the poor guy/girl can make sense out of the mountains of logs that get printed all the time in order to find the messages there. 

If there is anything to debug for the end user, such as why the device isn't working, then that should be displayed in the client. I can imagine adding a few error codes to the init function that would indicate what has happened so that the client could handle it, even though there isn't a lot of info available (basically no 6DOF device found/no joystick found, failed to open device file). However, this would need to be coordinated with what the original library returns, so that it remains compatible.

 However, printing debug info in the form of hexadecimal numbers for the detected buttons is not useful, in my opinion. That doesn't tell the user anything in case of failure and is useless when things actually work.

**Pull request merged**
