### PR TITLE
Update ndofdev.c

### PR DESCRIPTION
**Pull request by KaiWerthwein**
Added the ID for my new Spacemouse Compact, maybe you like to integrate it
12:40:38 kernel: hid-generic 0003:256F:C635.0008: input,hidraw4: USB HID v1.11 Multi-Axis Controller [3Dconnexion SpaceMouse Compact] on usb-0000:11:00.3-2.4/input0
12:40:38 kernel: input: 3Dconnexion SpaceMouse Compact as /devices/pci0000:00/0000:00:07.1/0000:11:00.3/usb5/5-2/5-2.4/5-2.4:1.0/0003:256F:C635.0008/input/input20
12:40:37 kernel: usb 5-2.4: Manufacturer: 3Dconnexion

### CODE REVIEW

**Comment by KaiWerthwein** [comment]
Hello Jan,
maybe you like to add a new device.

Thanks,
Kai

**Comment by janoc** [comment]
Cool, thank you very much! Now I have to go harass the Firestorm developers to update their copy again :)

**Comment by KaiWerthwein** [comment]
Hello Jan,

sure thing.. if or when you have a ticket No. i upvote it.

KR,
Kai

Am Di., 6. Nov. 2018 um 09:52 Uhr schrieb Jan Ciger <
notifications@github.com>:

**Comment by janoc** [comment]
You can try here: https://jira.phoenixviewer.com/browse/FIRE-23254

**Pull request merged**
